import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import Footer from '@/components/footer';
import Navbar from '@/components/navigation/navbar';
import { QueryClientProvider } from '@tanstack/react-query';
import queryClient from '@/lib/queryClient';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <div className='relative bg-primary text-primary-foreground z-50'>
            <Navbar />
          </div>
          <main className='mt-16 px-5 md:px-8 lg:px-10'>{children}</main>
          <Toaster />
          <footer className='bg-primary text-primary-foreground'>
            <Footer />
          </footer>
        </QueryClientProvider>
      </body>
    </html>
  );
}
